apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: hospital-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web
        image: prod-web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
